### PR TITLE
Add description of client registration variables/properties

### PR DESCRIPTION
**Pull request by federicaagostini**
In particular:
- IAM_CLIENT_REGISTRATION_ALLOW_FOR
- IAM_CLIENT_REGISTRATION_ENABLE
- IAM_DEFAULT_ACCESS_TOKEN_VALIDITY_SECONDS
- IAM_DEFAULT_DEVICE_CODE_VALIDITY_SECONDS
- IAM_DEFAULT_ID_TOKEN_VALIDITY_SECONDS
- IAM_DEFAULT_REFRESH_TOKEN_VALIDITY_SECONDS

### CODE REVIEW

**Comment by federicaagostini** [comment]
I've set this PR as draft since I don't know if we want to fix the already released but not advertized environment variables for AT, RT, ID token and device code lifetimes. In particular, @giacomini suggested to prefix all of them  with `IAM_`, as all of the other `iam:` properties.

Also, let me know if we also want to create another page to show how to configure the client-registration with an application.yml file (e.g. copy-and-paste plus explain [those properties](https://github.com/indigo-iam/iam/blob/master/iam-login-service/src/main/resources/application.yml#L220-L227)).

**Comment by rmiccoli** [comment]
> I've set this PR as draft since I don't know if we want to fix the already released but not advertized environment variables for AT, RT, ID token and device code lifetimes. In particular, @giacomini suggested to prefix all of them with `IAM_`, as all of the other `iam:` properties.
> 
> Also, let me know if we also want to create another page to show how to configure the client-registration with an application.yml file (e.g. copy-and-paste plus explain [those properties](https://github.com/indigo-iam/iam/blob/master/iam-login-service/src/main/resources/application.yml#L220-L227)).

I agree to rename those variables by adding the _IAM_ prefix.
Then, I think it is ok to explain the variables there as all other configurations are also listed.

**Review by rmiccoli — APPROVED** [review]

**Comment by federicaagostini** [comment]
> > I've set this PR as draft since I don't know if we want to fix the already released but not advertized environment variables for AT, RT, ID token and device code lifetimes. In particular, @giacomini suggested to prefix all of them with `IAM_`, as all of the other `iam:` properties.
> > Also, let me know if we also want to create another page to show how to configure the client-registration with an application.yml file (e.g. copy-and-paste plus explain [those properties](https://github.com/indigo-iam/iam/blob/master/iam-login-service/src/main/resources/application.yml#L220-L227)).
> 
> I agree to rename those variables by adding the _IAM_ prefix. 

This should be solved with https://github.com/indigo-iam/iam/pull/807

> Then, I think it is ok to explain the variables there as all other configurations are also listed.

**Comment by federicaagostini** [comment]
> Then, I think it is ok to explain the variables there as all other configurations are also listed.

Done

**Review by enricovianello — APPROVED** [review]

**Pull request merged**
